export const ROLE_SELECT = 'ROLE_SELECT';
export const ROLE_RESET = 'ROLE_RESET';

export const RESOURCE_FETCH_REQUESTED = 'RESOURCE_FETCH_REQUESTED';
export const RESOURCE_FETCH_START = 'RESOURCE_FETCH_START';
export const RESOURCE_FETCH_SUCCESS = 'RESOURCE_FETCH_SUCCESS';


export const RESOURCE_FETCH_ERROR = 'RESOURCE_FETCH_ERROR';
export const RESOURCE_FETCH_END = 'RESOURCE_FETCH_END';

export const RESOURCE_LIST = 'RESOURCE_LIST'

export const SNACKBAR_SHOW = 'SNACKBAR_SHOW';
export const SNACKBAR_HIDE = 'SNACKBAR_HIDE';

export const DIALOG_SHOW = 'DIALOG_SHOW';
export const DIALOG_TITLE_CHANGE = 'DIALOG_TITLE_CHANGE';
export const DIALOG_SAVE = 'DIALOG_SAVE';
export const DIALOG_REVERT = 'DIALOG_REVERT';
export const DIALOG_HIDE = 'DIALOG_HIDE';
export const DIALOG_MODIFY = 'DIALOG_MODIFY';

export const FAQ_TOGGLE = 'FAQ_TOGGLE';
export const FAQ_URL = 'FAQ_URL';

export const DRAWER_SHOW = 'DRAWER_SHOW';
export const DRAWER_HIDE = 'DRAWER_HIDE';

export const CART_ITEM_ADD = 'CART_ITEM_ADD';
export const CART_ITEM_REMOVE = 'CART_ITEM_REMOVE';
export const CART_RESET = 'CART_RESET';
export const CART_VALIDATE = 'CART_VALIDATE';

export const BOOTH_CHECKED = 'BOOTH_CHECKED';
export const BOOTH_SELECT = 'BOOTH_SELECT';
export const BOOTH_UNSELECT = 'BOOTH_UNSELECT';
export const BOOTHS_RESET = 'BOOTHS_RESET';

export const SEARCH_STARTED = 'SEARCH_STARTED';





export const VOTE_REQUESTED = 'VOTE_REQUESTED';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const VOTE_ERROR = 'VOTE_ERROR';

export const VOTE_STATUS_CHECK = 'VOTE_STATUS_CHECK';
export const VOTE_STATUS_SUCCESS = 'VOTE_STATUS_SUCCESS';
export const VOTE_STATUS_ERROR = 'VOTE_STATUS_ERROR';



export const LINKEDIN_TOKEN_RESET = 'LINKEDIN_TOKEN_RESET';
export const LINKEDIN_TOKEN_SUCCESS = 'LINKEDIN_TOKEN_SUCCESS';
export const LINKEDIN_TOKEN_FAILURE = 'LINKEDIN_TOKEN_FAILURE';

export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const REMOVE_USER_TOKEN = 'REMOVE_USER_TOKEN';



export const LINKEDIN_VOTE_REQUESTED = 'LINKEDIN_VOTE_REQUESTED';
export const LINKEDIN_AUTOVOTE_REQUESTED = 'LINKEDIN_AUTOVOTE_REQUESTED';
export const LINKEDIN_VOTE_SUCCESS = 'LINKEDIN_VOTE_SUCCESS';
export const LINKEDIN_VOTE_ERROR = 'LINKEDIN_VOTE_ERROR';

export const PAGE_LOADING_START = 'PAGE_LOADING_START'
export const PAGE_LOADING_END = 'PAGE_LOADING_END'

export const PAGE_ACTION_SHOW = 'PAGE_ACTION_SHOW'
export const PAGE_ACTION_HIDE = 'PAGE_ACTION_HIDE'


export const UUID_SET = 'UUID_SET'

export const LOCK_FAILED = 'LOCK_FAILED';
export const LOCK_SUCCESS = 'LOCK_SUCCESS';

export const USER_INTERACTED_WITH = 'USER_INTERACTED_WITH'